{
 "title": "Sungrow EyeM4 Exporter",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Daily Yield",
   "type": "stat",
   "description": "So far today",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "eyem4_realtime_data_daily_yield{ip=\"192.168.1.175\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Yield",
   "type": "stat",
   "description": "Lifetime yield so far",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "eyem4_realtime_data_total_yield{ip=\"192.168.1.175\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Feed-in Power",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "eyem4_realtime_data_feedin_power{ip=\"192.168.1.175\", device_type=\"18\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total DC Power",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "eyem4_realtime_data_total_dc_power{ip=\"192.168.1.175\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Power",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "eyem4_realtime_data_active_power{ip=\"192.168.1.175\", device_type=\"18\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Reactive Power",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kvoltampreact" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "eyem4_realtime_data_reactive_power{ip=\"192.168.1.175\", device_type=\"18\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Power Factor (PF)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "eyem4_realtime_data_pf{ip=\"192.168.1.175\", device_type=\"18\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Interior Temperature",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "eyem4_realtime_data_interior_temperature{ip=\"192.168.1.175\"}",
     "legendFormat": "Interior Temperature"
    }
   ]
  },
  {
   "title": "Daily Yield",
   "type": "stat",
   "description": "$0.13441 per KWh",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "eyem4_realtime_data_daily_yield{ip=\"192.168.1.175\"} * 0.13441",
     "legendFormat": "Daily Yield"
    }
   ]
  },
  {
   "title": "Total Yield",
   "type": "stat",
   "description": "$0.13441 per KWh",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "eyem4_realtime_data_total_yield{ip=\"192.168.1.175\"} * 0.13441",
     "legendFormat": "Daily Yield"
    }
   ]
  },
  {
   "title": "Total PV Current",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "eyem4_dc_data_string_1_current{ip=\"192.168.1.175\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "eyem4_dc_data_string_2_current{ip=\"192.168.1.175\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "eyem4_dc_data_string_3_current{ip=\"192.168.1.175\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "eyem4_dc_data_string_4_current{ip=\"192.168.1.175\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "eyem4_dc_data_string_5_current{ip=\"192.168.1.175\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "eyem4_dc_data_string_6_current{ip=\"192.168.1.175\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Forward Active Energy",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "eyem4_realtime_data_forward_active_energy{ip=\"192.168.1.175\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Reverse Active Energy",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "eyem4_realtime_data_reverse_active_energy{ip=\"192.168.1.175\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Apparent Power",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "kvoltamp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "eyem4_realtime_data_total_apparent_power{ip=\"192.168.1.175\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PV Current",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "expr": "eyem4_dc_data_string_1_current{ip=\"192.168.1.175\"}",
     "legendFormat": "String 1"
    },
    {
     "expr": "eyem4_dc_data_string_2_current{ip=\"192.168.1.175\"}",
     "legendFormat": "String 2"
    },
    {
     "expr": "eyem4_dc_data_string_3_current{ip=\"192.168.1.175\"}",
     "legendFormat": "String 3"
    },
    {
     "expr": "eyem4_dc_data_string_4_current{ip=\"192.168.1.175\"}",
     "legendFormat": "String 4"
    },
    {
     "expr": "eyem4_dc_data_string_5_current{ip=\"192.168.1.175\"}",
     "legendFormat": "String 5"
    },
    {
     "expr": "eyem4_dc_data_string_6_current{ip=\"192.168.1.175\"}",
     "legendFormat": "String 6"
    }
   ]
  },
  {
   "title": "Phase Voltage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "expr": "eyem4_realtime_data_phase_a_voltage{ip=\"192.168.1.175\", device_type=\"18\"}",
     "legendFormat": "Phase A"
    },
    {
     "expr": "eyem4_realtime_data_phase_b_voltage{ip=\"192.168.1.175\", device_type=\"18\"}",
     "legendFormat": "Phase B"
    },
    {
     "expr": "eyem4_realtime_data_phase_c_voltage{ip=\"192.168.1.175\", device_type=\"18\"}",
     "legendFormat": "Phase C"
    }
   ]
  },
  {
   "title": "Active Power",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "expr": "eyem4_realtime_data_active_power{ip=\"192.168.1.175\"}",
     "legendFormat": "Active Power"
    }
   ]
  },
  {
   "title": "Phase Current",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "expr": "eyem4_realtime_data_phase_a_current{ip=\"192.168.1.175\", device_type=\"18\"}",
     "legendFormat": "Phase A"
    },
    {
     "expr": "eyem4_realtime_data_phase_b_current{ip=\"192.168.1.175\", device_type=\"18\"}",
     "legendFormat": "Phase B"
    },
    {
     "expr": "eyem4_realtime_data_phase_c_current{ip=\"192.168.1.175\", device_type=\"18\"}",
     "legendFormat": "Phase C"
    }
   ]
  },
  {
   "title": "Total DC Power",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "targets": [
    {
     "expr": "eyem4_realtime_data_total_dc_power{ip=\"192.168.1.175\"}",
     "legendFormat": "Total DC Power"
    }
   ]
  },
  {
   "title": "Phase Active Power",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "targets": [
    {
     "expr": "eyem4_realtime_data_phase_a_active_power{ip=\"192.168.1.175\", device_type=\"18\"}",
     "legendFormat": "Phase A"
    },
    {
     "expr": "eyem4_realtime_data_phase_b_active_power{ip=\"192.168.1.175\", device_type=\"18\"}",
     "legendFormat": "Phase B"
    },
    {
     "expr": "eyem4_realtime_data_phase_c_active_power{ip=\"192.168.1.175\", device_type=\"18\"}",
     "legendFormat": "Phase C"
    }
   ]
  },
  {
   "title": "MPPT Voltage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "expr": "eyem4_dc_data_mppt1_voltage{ip=\"192.168.1.175\"}",
     "legendFormat": "MPPT 1"
    },
    {
     "expr": "eyem4_dc_data_mppt2_voltage{ip=\"192.168.1.175\"}",
     "legendFormat": "MPPT 2"
    },
    {
     "expr": "eyem4_dc_data_mppt3_voltage{ip=\"192.168.1.175\"}",
     "legendFormat": "MPPT 3"
    }
   ]
  },
  {
   "title": "MPPT Current",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "expr": "eyem4_dc_data_mppt1_current{ip=\"192.168.1.175\"}",
     "legendFormat": "MPPT 1"
    },
    {
     "expr": "eyem4_dc_data_mppt2_current{ip=\"192.168.1.175\"}",
     "legendFormat": "MPPT 2"
    },
    {
     "expr": "eyem4_dc_data_mppt3_current{ip=\"192.168.1.175\"}",
     "legendFormat": "MPPT 3"
    }
   ]
  }
 ]
}